using API.API.BC.Modelos;
using System.Collections.Generic;

namespace API.API.BC {
    public class GeneradorDePreguntas {

        public List<Pregunta> GeneraLasPreguntas(){
            List<Pregunta> preguntas = new List<Pregunta>{
                new Pregunta{Nombre = "Abbey Road", Foto= "/Imagenes/AbbeyRoad.jpg", Categoria = "Rock", IndexCateg = 1,
                    RespuestaCorrecta = false},
                new Pregunta{Nombre = "Atom Heart Mother", Foto= "/Imagenes/AHM.jpg", Categoria = "Rock", IndexCateg = 1,
                    RespuestaCorrecta = false},
                new Pregunta{Nombre = "AM", Foto= "/Imagenes/Am.png", Categoria = "Rock", IndexCateg = 1,
                    RespuestaCorrecta = false},
                new Pregunta{Nombre = "Californication", Foto= "/Imagenes/Californication.jpg", Categoria = "Rock",
                    IndexCateg = 1, RespuestaCorrecta = false},
                new Pregunta{Nombre = "El Silencio", Foto= "/Imagenes/ElSilencio.jpg", Categoria = "Rock",
                    IndexCateg = 1, RespuestaCorrecta = false},
                new Pregunta{Nombre = "In Utero", Foto= "/Imagenes/InUtero.jpg", Categoria = "Rock", IndexCateg = 1,
                    RespuestaCorrecta = false},
                new Pregunta{Nombre = "Mezmerize", Foto= "/Imagenes/Mezmerize.jpg", Categoria = "Rock", IndexCateg = 1,
                    RespuestaCorrecta = false},
                new Pregunta{Nombre = "Rammstein", Foto= "/Imagenes/Rammstein.jpg", Categoria = "Rock", IndexCateg = 1,
                    RespuestaCorrecta = false},
                new Pregunta{Nombre = "The Dark Side of the Moon", Foto= "/Imagenes/TDSOTM.png", Categoria = "Rock",
                    IndexCateg = 1, RespuestaCorrecta = false},
                new Pregunta{Nombre = "Funky kingston", Foto= "/Imagenes/FunkyKingston.jpg", Categoria = "Reggae",
                    IndexCateg = 2, RespuestaCorrecta = false},
                new Pregunta{Nombre = "Kaya", Foto= "/Imagenes/Kaya.jpg", Categoria = "Reggae", IndexCateg = 2,
                    RespuestaCorrecta = false},
                new Pregunta{Nombre = "Marcus Garvey", Foto= "/Imagenes/MarcusGarvey.jpg", Categoria = "Reggae",
                    IndexCateg = 2, RespuestaCorrecta = false},
                new Pregunta{Nombre = "Trenchtown Mix Up", Foto= "/Imagenes/TrenchtownMixUp.jpg", Categoria = "Reggae",
                    IndexCateg = 2, RespuestaCorrecta = false},
                new Pregunta{Nombre = "Super Ape", Foto= "/Imagenes/SuperApe.jpg", Categoria = "Reggae", IndexCateg = 2,
                    RespuestaCorrecta = false},
                new Pregunta{Nombre = "Distant Relative", Foto= "/Imagenes/DistantRelative.jpg", Categoria = "Reggae",
                    IndexCateg = 2, RespuestaCorrecta = false},
                new Pregunta{Nombre = "Best Dressed Chicken In Town", Foto= "/Imagenes/BDCIT.jpg", Categoria = "Reggae",
                    IndexCateg = 2, RespuestaCorrecta = false},
                new Pregunta{Nombre = "Conquering Lion", Foto= "/Imagenes/ConqueringLion.jpg", Categoria = "Reggae",
                    IndexCateg = 2, RespuestaCorrecta = false},
                new Pregunta{Nombre = "King Tubbys Presents Soundclash Dubplate Style", Foto= "/Imagenes/KTPSD.jpg",
                    Categoria = "Reggae", IndexCateg = 2, RespuestaCorrecta = false},
                new Pregunta{Nombre = "Shawn Mendes", Foto= "/Imagenes/ShawnMendes.png", Categoria = "Pop",
                    IndexCateg = 3, RespuestaCorrecta = false},
                new Pregunta{Nombre = "Caution", Foto= "/Imagenes/Caution.png", Categoria = "Pop", IndexCateg = 3,
                    RespuestaCorrecta = false},
                new Pregunta{Nombre = "Bloom", Foto= "/Imagenes/Bloom.jpg", Categoria = "Pop", IndexCateg = 3,
                    RespuestaCorrecta = false},
                new Pregunta{Nombre = "Dancing Queen", Foto= "/Imagenes/DancingQueen.jpg", Categoria = "Pop",
                    IndexCateg = 3, RespuestaCorrecta = false},
                new Pregunta{Nombre = "Sweetener", Foto= "/Imagenes/Sweetener.png", Categoria = "Pop", IndexCateg = 3,
                    RespuestaCorrecta = false},
                new Pregunta{Nombre = "Golden", Foto= "/Imagenes/Golden.png", Categoria = "Pop", IndexCateg = 3,
                    RespuestaCorrecta = false},
                new Pregunta{Nombre = "Voicenotes", Foto= "/Imagenes/Voicenotes.jpg", Categoria = "Pop", IndexCateg = 3,
                    RespuestaCorrecta = false},
                new Pregunta{Nombre = "Liberation", Foto= "/Imagenes/Liberation.png", Categoria = "Pop", IndexCateg = 3,
                    RespuestaCorrecta = false},
                new Pregunta{Nombre = "Thriller", Foto= "/Imagenes/Thriller.jpg", Categoria = "Pop", IndexCateg = 3,
                    RespuestaCorrecta = false},
                new Pregunta{Nombre = "The Marshall Mathers LP", Foto= "/Imagenes/TheMarshallMathersLP.jpg",
                    Categoria = "Rap/HipHop", IndexCateg = 4, RespuestaCorrecta = false},
                new Pregunta{Nombre = "Me Against The World", Foto= "/Imagenes/MeAgainstTheWorld.jpg",
                    Categoria = "Rap/HipHop", IndexCateg = 4, RespuestaCorrecta = false},
                new Pregunta{Nombre = "The Eminem Show", Foto= "/Imagenes/TheEminemShow.jpg", Categoria = "Rap/HipHop",
                    IndexCateg = 4, RespuestaCorrecta = false},
                new Pregunta{Nombre = "All Eyez On Me", Foto= "/Imagenes/AllEyezOnMe.jpg", Categoria = "Rap/HipHop",
                    IndexCateg = 4, RespuestaCorrecta = false},
                new Pregunta{Nombre = "Stillmatic", Foto= "/Imagenes/Stillmatic.jpg", Categoria = "Rap/HipHop",
                    IndexCateg = 4, RespuestaCorrecta = false},
                new Pregunta{Nombre = "Black On Both Sides", Foto= "/Imagenes/BlackOnBothSides.jpg",
                    Categoria = "Rap/HipHop", IndexCateg = 4, RespuestaCorrecta = false},
                new Pregunta{Nombre = "Black Sunday", Foto= "/Imagenes/BlackSunday.jpg", Categoria = "Rap/HipHop",
                    IndexCateg = 4, RespuestaCorrecta = false},
                new Pregunta{Nombre = "Things Fall Apart", Foto= "/Imagenes/ThingsFallApart.jpg",
                    Categoria = "Rap/HipHop", IndexCateg = 4, RespuestaCorrecta = false},
                new Pregunta{Nombre = "Aquemini", Foto= "/Imagenes/Aquemini.jpg", Categoria = "Rap/HipHop",
                    IndexCateg = 4, RespuestaCorrecta = false},
            };

            return preguntas;
        }
    }
}
